server:
  port : 9080
spring :
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1
    username: kyobo
    password: kyobo11!
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/donots_batch
      username: kyobo
      password: kyobo11!
      driver-class-name: org.postgresql.Driver
      data-source-properties :
        rewriteBatchedStatements: true
  #  session:
  #     store-type: redis
  #  redis:
  #     host: donots-redis.mpt7r0.clustercfg.apn2.cache.amazonaws.com
  #     port: 6379
  #     database: 0
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true